// framework-enhancement-tests/react/menu/main.tsx
/** @jsxImportSource react */
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { MenuElement } from "@itenthusiasm/custom-elements";
import MenuExample from "./MenuExample.jsx";

if (!customElements.get("menu-element")) customElements.define("menu-element", MenuElement);

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <MenuExample />
  </StrictMode>,
);

// framework-enhancement-tests/solid/menu/index.tsx
/** @jsxImportSource solid-js */
import { render } from "solid-js/web";
import { MenuElement } from "@itenthusiasm/custom-elements";
import MenuExample from "./MenuExample.jsx";

if (!customElements.get("menu-element")) customElements.define("menu-element", MenuElement);

const root = document.getElementById("root");
render(() => <MenuExample />, root!);
