// framework-enhancement-tests/svelte/ExampleForm.svelte
<form>
  <Select name="ranking" filter>
    {#each options as rank, i}
      <Option value={`${i + 1}`} selected={i === 2}>
        {rank}
      </Option>
    {/each}
  </Select>
</form>

<script lang="ts">
  import Select from "./Select.svelte";
  import Option from "./Option.svelte";

  const options = ["First", "Second", "Third", "Fourth", "Fifth"];
</script>

// framework-enhancement-tests/solid/ExampleForm.tsx
/** @jsxImportSource solid-js */
import { For } from "solid-js";
import Select, { Option } from "./Select.jsx";

export default function ExampleForm() {
  const options = ["First", "Second", "Third", "Fourth", "Fifth"];

  return (
    <form>
      <Select name="ranking" filter>
        <For each={options}>
          {(rank, i) => (
            <Option value={i() + 1} bool:selected={i() === 2}>
              {rank}
            </Option>
          )}
        </For>
      </Select>
    </form>
  );
}
