// framework-enhancement-tests/vue/ExampleForm.vue
<script lang="ts" setup>
import Select from "./Select.vue";
import Option from "./Option.vue";

const options = ["First", "Second", "Third", "Fourth", "Fifth"];
</script>

<template>
  <form>
    <Select name="ranking" filter>
      <Option v-for="(rank, i) in options" :value="i + 1" :selected="i === 2">
        {{ rank }}
      </Option>
    </Select>
  </form>
</template>

// framework-enhancement-tests/svelte/ExampleForm.svelte
<form>
  <Select name="ranking" filter>
    {#each options as rank, i}
      <Option value={`${i + 1}`} selected={i === 2}>
        {rank}
      </Option>
    {/each}
  </Select>
</form>

<script lang="ts">
  import Select from "./Select.svelte";
  import Option from "./Option.svelte";

  const options = ["First", "Second", "Third", "Fourth", "Fifth"];
</script>
