// framework-enhancement-tests/solid/menu/index.tsx
/** @jsxImportSource solid-js */
import { render } from "solid-js/web";
import { MenuElement } from "@itenthusiasm/custom-elements";
import MenuExample from "./MenuExample.jsx";

if (!customElements.get("menu-element")) customElements.define("menu-element", MenuElement);

const root = document.getElementById("root");
render(() => <MenuExample />, root!);

// framework-enhancement-tests/preact/menu/main.tsx
/** @jsxImportSource preact */
import { render } from "preact";
import { MenuElement } from "@itenthusiasm/custom-elements";
import type {} from "@itenthusiasm/custom-elements/types/preact.d.ts";
import MenuExample from "./MenuExample.jsx";

if (!customElements.get("menu-element")) customElements.define("menu-element", MenuElement);

render(<MenuExample />, document.getElementById("app")!);
