// framework-enhancement-tests/react/ExampleForm.tsx
import Select, { Option } from "./Select.jsx";

export default function ExampleForm() {
  const options = ["First", "Second", "Third", "Fourth", "Fifth"];

  return (
    <form>
      <Select name="ranking" filter>
        {options.map((rank, i) => (
          <Option key={rank} value={`${i + 1}`} defaultSelected={i === 2}>
            {rank}
          </Option>
        ))}
      </Select>
    </form>
  );
}

// framework-enhancement-tests/vue/ExampleForm.vue
<script lang="ts" setup>
import Select from "./Select.vue";
import Option from "./Option.vue";

const options = ["First", "Second", "Third", "Fourth", "Fifth"];
</script>

<template>
  <form>
    <Select name="ranking" filter>
      <Option v-for="(rank, i) in options" :value="i + 1" :selected="i === 2">
        {{ rank }}
      </Option>
    </Select>
  </form>
</template>
